name: Gradle Plugin Publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Check Tag
      run: echo $GITHUB_REF

    - name: write key
        run: echo $GRADLE_PUBLISH_KEY

    - name: Write gradle.properties
      env:
        KEY: ${{ env.GRADLE_PUBLISH_KEY }}
        SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
        echo gradle.publish.key=${KEY} > ~/.gradle/gradle.properties
        echo gradle.publish.secret=${SECRET} > ~/.gradle/gradle.properties

    - name: Build with Gradle
      run: gradle build

    - name: Publish to Gradle
      run: gradle publishPlugins
      env:
        key: $GRADLE_PUBLISH_KEY
        secret: $GRADLE_PUBLISH_SECRET

