name: Gradle Plugin Publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Check Tag
      run: echo GITHUB_REF

    - name: Build with Gradle
      run: gradle build

    - name: Publish to Gradle
      run: gradle publishPlugins
      env:
        key: ${{ env.GRADLE_KEY }}
        secret: ${{ env.GRADLE_SECRET }}
